// air-pollutant-map/src/components/OlMap.vue
<template>
  <div>
    <div id="ol-map">
      <OlGridDataLayer
        v-if="gnfrId && pollutant && isReady && mapDataType === mapDataTypes.GRID"
        :year="year"
        :gnfrId="gnfrId"
        :pollutant="pollutant"
        :map="map"
        @update-legend="updateLegend"
        @set-grid-feature-popup="setGridFeaturePopup"
        @update-total-emission-stats="(tps) => $emit('update-total-emission-stats', tps)"
      />
    </div>
    <Legend id="map-legend-container" :legend="legend" :mapDataType="mapDataType" />
    <div class="olpopup" ref="olpopup" v-show="gridPopupValue">
      <GridFeaturePopup
        v-if="gridPopupValue"
        :popupValue="gridPopupValue"
        :pollutant="pollutant"
        @close-popup="closePopup"
      />
    </div>
  </div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import Map from "ol/Map.js";
import View from "ol/View.js";
import { Tile as TileLayer } from 'ol/layer';
import WMTS from "ol/source/WMTS";
import WMTSTileGrid from "ol/tilegrid/WMTS";
import TileWMS from "ol/source/TileWMS";
import Overlay from "ol/Overlay";
import { Coordinate } from "ol/coordinate";
import { Extent } from "ol/extent";
import OlGridDataLayer from "./OlGridDataLayer.vue";
import GridFeaturePopup from "./GridFeaturePopup.vue";
import Legend from "./Legend.vue";
import { Pollutant, MapDataType } from "@/types";
import { PollutantLegend } from "../types";
import Projection from "ol/proj/Projection";
import * as env from "../env";

const projection = new Projection({
  code: "EPSG:3067",
  extent: [50199.4814, 6582464.0358, 761274.6247, 7799839.8902],
  global: false,
  metersPerUnit: 1
});

export default Vue.extend({
  components: {
    OlGridDataLayer,
    GridFeaturePopup,
    Legend
  },
  props: {
    year: Number,
    gnfrId: String,
    pollutant: { type: Object as PropType<Pollutant | undefined> },
    mapDataType: { type: String as PropType<MapDataType> }
  },
  data() {
    return {
      map: undefined as Map | undefined,
      isReady: false as boolean,
      mapDataTypes: Object(MapDataType),
      overlay: null as Overlay | null,
      popupCoords: undefined as Coordinate | undefined,
      gridPopupValue: null as number | null,
      legend: undefined as PollutantLegend | undefined
    };
  },
  watch: {
    year() {
      this.handlePopupOnLayerChange();
    },
    gnfrId() {
      this.handlePopupOnLayerChange();
    },
    pollutant() {
      this.handlePopupOnLayerChange();
    }
  },
  methods: {
    handlePopupOnLayerChange() {
      if (this.mapDataType === MapDataType.GRID) {
        this.closePopup();
      }
    },
    updateLegend(legend: PollutantLegend) {
      this.legend = legend;
    },
    initializePopup() {
      this.overlay = new Overlay({
        // @ts-ignore
        element: this.$refs.olpopup, // popup tag, in html
        autoPan: true, // If the pop-up window is at the edge of the base image, the base image will move
        autoPanAnimation: {
          // Basemap moving animation
          duration: 250
        }
      });
      if (this.map) {
        this.map.addOverlay(this.overlay);
      }
    },
    setGridFeaturePopup(coordinate: Coordinate | undefined, value: number | null) {
      this.gridPopupValue = value;
      setTimeout(() => {
        // Set the timer here, otherwise the pop-up window will appear for the first time, and the base map will be off-track
        if (this.overlay) {
          this.overlay.setPosition(coordinate);
          this.popupCoords = coordinate;
        }
      }, 0);
    },

    closePopup() {
      // Set the position of the pop-up window to undefined, and clear the coordinate data
      if (this.overlay) {
        this.overlay.setPosition(undefined);
      }
      this.popupCoords = undefined;
      this.gridPopupValue = null;
    }
  },
  mounted() {
    const areaSize = 2097152; // width and height of the matrix set in ground (from capabilities)
    const tileSize = 256; // width and height of the tile in pixels (from capabilities)
    const matrixIds = new Array(18);
    const resolutions = new Array(18);
    const proxyUrl = "https://paikkatieto.ymparisto.fi/proxy/proxy.ashx?";

    for (let z = 0; z < 16; ++z) {
      matrixIds[z] = z;
      resolutions[z] = areaSize / tileSize / Math.pow(2, z);
    }


    const baseLayer = new TileLayer({
      zIndex: 13,
      source: new TileWMS({
        url: env.gsUri + "ows",
        params: { LAYERS: "shoreline", TILED: true },
        serverType: "geoserver",
        attributions: "© MML, 2011",
      }),
    });

    this.map = new Map({
      target: "ol-map",
      layers: [baseLayer],
      view: new View({
        projection,
        center: [435385.0836878328, 7247696.528687431],
        extent: [-166488.7651729983, 6568916.617733785, 1037258.9325486642, 7903739.064762917],
        zoom: 1,
        showFullExtent: true
      })
    });
    this.map.once("postrender", () => {
      this.isReady = true;
      const extent = [
        -32010.40984326898,
        6590316.535987211,
        902780.5772189347,
        7905076.52138765
      ] as Extent;
      this.map!.getView().fit(extent, { padding: [15, 0, 0, 0] });
    });
    this.initializePopup();
    console.log("map", this.map);
  }
});
</script>

<style scoped>
@import "~ol/ol.css";
#ol-map {
  height: calc(100vh - 260px);
  width: 100%;
  z-index: 0;
}
@media (max-height: 900px) {
  #ol-map {
    height: max(70vh, 400px);
  }
}
@media (max-width: 516px) {
  #ol-map {
    background-color: #fbfbfb;
  }
}
@media (min-width: 1200px) {
  #ol-map {
    height: calc(100vh - 44px);
  }
}
#map-legend-container {
  position: absolute;
  top: 10px;
  right: 10px;
  z-index: 2;
}

/* Pop-up window style */
.olpopup {
  min-width: max-content;
  position: absolute;
  background: #fff;
  padding: 8px 16px;
  border-radius: 10px;
  border: 1px solid #cccccc;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2);
  display: flex;
  flex-direction: column;
  transform: translate(-50%, calc(-100% - 12px));
}
/* The small triangle below the pop-up window */
.olpopup:after,
.olpopup:before {
  display: block;
  content: "";
  width: 0;
  height: 0;
  position: absolute;
  border: 12px solid transparent;
  border-top-color: #fff;
  bottom: -23px;
  left: 50%;
  transform: translateX(-50%);
}
</style>

// ui/src/components/OlMap.tsx
import { useEffect, useRef, useState } from 'react'
import { CloseButton } from '@chakra-ui/close-button'
import { Map, Overlay, View } from 'ol'
import TileLayer from 'ol/layer/Tile'
import WMTS from 'ol/source/WMTS'
import WMTSTileGrid from 'ol/tilegrid/WMTS'
import { Extent } from 'ol/extent'
import Projection from 'ol/proj/Projection'
import { easeOut } from 'ol/easing'
import 'ol/ol.css'
import './OlMap.css'
import { Box, Flex } from '@chakra-ui/layout'
import { FacilityMapFeature } from '../models/FacilityMapFeature'
import { FacilityWithCoordinates } from '../api/models/Facility'
import { facilityLayer, OlLayerFacilities } from './OlLayerFacilities'
import { FacilityMapPopupContent } from './FacilityMapPopupContent'

const initialExtent = [-32010, 6570316, 902780, 7835076] as Extent

const etrsTm35Fin = new Projection({
  code: 'EPSG:3067',
  extent: [50199.4814, 6582464.0358, 761274.6247, 7799839.8902],
  global: false,
  metersPerUnit: 1
})

const areaSize = 2097152; // width and height of the matrix set in ground (from capabilities)
const tileSize = 256; // width and height of the tile in pixels (from capabilities)
const matrixIds = new Array(18);
const resolutions = new Array(18);
const proxyUrl = 'https://paikkatieto.ymparisto.fi/proxy/proxy.ashx?';

for (let z = 0; z < 16; ++z) {
  matrixIds[z] = z;
  resolutions[z] = areaSize / tileSize / Math.pow(2, z);
}

const baseLayer = new TileLayer({
  zIndex: 1,
  source: new WMTS({
    url: proxyUrl + 'https://karttakuva.maanmittauslaitos.fi/maasto/wmts?x',
    layer: 'taustakartta',
    matrixSet: 'ETRS-TM35FIN',
    style: 'default',
    tileGrid: new WMTSTileGrid({
      matrixIds: matrixIds,
      resolutions: resolutions,
      origin: [-548576, 8388608] // from capabilities
    }),
    attributions: '© Maanmittauslaitos'
  })
})

const olMap = new Map({
  target: undefined,
  layers: [baseLayer, facilityLayer],
  view: new View({
    projection: etrsTm35Fin,
    center: [435385, 7247696],
    extent: [-266488, 6468916, 1137258, 7903739],
    zoom: 1.5
  })
})

const popupOverlay = new Overlay({
  autoPan: true, // If the pop-up window is at the edge of the base image, the base image will move
  autoPanAnimation: {
    // Basemap moving animation
    duration: 250
  }
})

olMap.on('pointermove', e => {
  const pixel = olMap.getEventPixel(e.originalEvent)
  const hit = olMap.hasFeatureAtPixel(pixel, {
    layerFilter: l => l.get('name') === 'facilities'
  })
  const canvas = document.querySelector('canvas')
  if (canvas) {
    canvas.style.cursor = hit ? 'pointer' : ''
  }
})

interface Props {
  facilities?: FacilityWithCoordinates[]
  width?: number
  margin?: number
  height?: string | number
  zoomToInitialExtent: boolean
}

export const OlMap = (props: Props) => {
  const mapRef = useRef<HTMLDivElement>(null)
  const popupRef = useRef<HTMLDivElement>(null)
  const [mapIsRendered, setMapIsRendered] = useState(false)
  const [popupData, setPopupData] = useState<FacilityMapFeature | null>(null)

  useEffect(() => {
    // initialize popup overlay when the target element mounts in the DOM
    if (popupRef.current) {
      olMap.addOverlay(popupOverlay)
      popupOverlay.setElement(popupRef.current)
    }
    return () => {
      setPopupData(null)
      popupOverlay.setElement(undefined)
      popupOverlay.setPosition(undefined)
      olMap.removeOverlay(popupOverlay)
    }
  }, [popupRef])

  useEffect(() => {
    // update/clear popup location when popupData is changed
    if (mapIsRendered) {
      if (popupData) {
        popupOverlay.setPosition(popupData.geometry.getCoordinates())
      } else {
        popupOverlay.setPosition(undefined)
      }
    }
  }, [popupData, mapIsRendered])

  useEffect(() => {
    // initialize map
    let renderDelay: null | ReturnType<typeof setTimeout> = null
    if (!olMap.getTarget() && mapRef.current) {
      olMap.setTarget(mapRef.current)
      renderDelay = setTimeout(() => {
        olMap.updateSize()
        setMapIsRendered(true)
      }, 100)
    }

    return () => {
      olMap.setTarget(undefined)
      if (!!renderDelay) clearTimeout(renderDelay)
      setMapIsRendered(false)
    }
  }, [mapRef])

  useEffect(() => {
    if (mapIsRendered && props.zoomToInitialExtent) {
      olMap.getView().fit(initialExtent, {
        padding: [100, 100, 100, 100],
        duration: 1000,
        easing: easeOut
      })
    }
  }, [mapIsRendered, props.zoomToInitialExtent])

  const facilityCount = props.facilities?.length

  return (
    <Box
      ref={mapRef}
      border="2px solid white"
      width={props.width || '600px'}
      minWidth={250}
      maxWidth="100%"
      margin={props.margin || 0}
      height={props.height || 'max(600px, calc(100vh - 345px))'}
      maxHeight={props.height || 1000}
      background="white"
      borderRadius="md"
      boxShadow="md">
      <Box
        ref={popupRef}
        className="ol-popup"
        visibility={popupData ? 'unset' : 'hidden'}
        p={4}>
        <Flex>
          <Box flex={1}>
            {popupData && <FacilityMapPopupContent popupData={popupData} />}
          </Box>
          <Box>
            <CloseButton onClick={() => setPopupData(null)} />
          </Box>
        </Flex>
      </Box>
      {mapIsRendered && !!facilityCount && (
        <OlLayerFacilities
          olMap={olMap}
          facilities={props.facilities!}
          popupData={popupData}
          setPopupData={setPopupData}
          zoomToInitialExtent={props.zoomToInitialExtent}
        />
      )}
    </Box>
  )
}
